### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by vivandoshi08** [Twometer/among-us-3d#4]
When I click the camera(which is colored yellow when my cursor is on it) no matter how many times i click it nothing happens.
Can you fix this in your next update.

**Comment by Twometer** [comment]
Yeah, the cameras are not yet implemented, this will be fixed in one of the next updates!

**Comment by vivandoshi08** [comment]
ok thats fine. Thanks for responding.

**Comment by vivandoshi08** [comment]
When do you think the next update will come?

**Comment by Twometer** [comment]
I don't really have a release plan, since this was just a hobby project of mine to play with some friends ;D but hopefully in the next few weeks I will release the fix for this.

**Comment by vivandoshi08** [comment]
Also how do i run it from source. 
I would like to change some of the code and add things like the camera function and new map models. I can even request a pr and push my code here as well. 
So could you explain how to run it from source.

**Comment by daniel-lerch** [comment]
Running Among Us 3D from source ist fairly easy but only if you know which steps to take. Because other contributors will have the same question, I won't answer here, but made a pull request to add build instructions to the README: #5

Just one advice for GitHub issues @vivandoshi08: Don't recycle them for a different problem. Just open a new issue because maintainers will consider closed issues as closed 😉

**Comment by Twometer** [comment]
I renamed the issue back to the cameras not working. 
@daniel-lerch has kindly added build instructions to the README file. If those don't work, please open a new issue for that :D

**Comment by vivandoshi08** [comment]
Thanks for the feedback. I will now start coding the camera system and create the polus map. 
:D
